{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cb373c78",
   "metadata": {},
   "outputs": [],
   "source": [
    "#This code was made with a partner at my school.\n",
    "\n",
    "#We will ask how much a summative contributes to their overall grade(Ex. 75%). This will be assigned a variable value (percentsummative).\n",
    "\n",
    "def percent_input():\n",
    "  classname = input(\"What is the name of the class you want your grade calculated for? \")\n",
    "  percentsummative = int(input(\"How much percent do Summatives contribute to your overall grade?: \"))\n",
    "  while percentsummative > 100 or percentsummative < 0:\n",
    "      print(\"Input can't be greater than 100 or less than 0\")\n",
    "      percentsummative = int(input(\"How much percent do Summatives contribute to your overall grade?: \"))\n",
    "      \n",
    "  #We will ask how much a formative contributes to their overall grade(Ex. 75%). This will be assigned a variable value (percentformative).\n",
    "                                   \n",
    "  percentformative = int(input(\"How much percent do Formatives contribute to your overall grade?: \"))\n",
    "  while percentformative > 100 or percentformative < 0:\n",
    "    print(\"Input can't be greater than 100 or less than 0\")\n",
    "    percentformative = int(input(\"How much percent do Summatives contribute to your overall grade?: \"))\n",
    "  #This will check if the two weight properly add up to 1, representing 100%.\n",
    "  if percentformative + percentsummative != 100:\n",
    "    print(\"Summative and Formative weights don't add up to 100\")\n",
    "    while percentformative + percentsummative != 100:\n",
    "      percentsummative = int(input(\"How much percent do Summatives contribute to your overall grade?: \"))\n",
    "      percentformative = int(input(\"How much percent do Formatives contribute to your overall grade?: \"))\n",
    "    \n",
    "  return classname, percentsummative, percentformative\n",
    "\n",
    "def summative_input():\n",
    "  summatives_taken = 0\n",
    "  summatives_taken = int(input( \"How many summative grades have you taken?: \"))\n",
    "  while summatives_taken < 0: \n",
    "      print(\"Input can't be greater than 100 or less than 0\")\n",
    "      summatives_taken = int(input( \"How many summative grades have you taken?: \"))\n",
    "  return summatives_taken\n",
    "  \n",
    "def formative_input():\n",
    "  formatives_taken = 0\n",
    "  formatives_taken = int(input( \"How many formative grades have you taken?: \"))\n",
    "  #We will have an input that asks how many summative grades the student has taken\n",
    "  while formatives_taken < 0: \n",
    "      print(\"Input can't be greater than 100 or less than 0\")\n",
    "      formatives_taken = int(input( \"How many formative grades have you taken?: \"))\n",
    "  return formatives_taken\n",
    "\n",
    "  \n",
    "def summative_calculations(percentsummative, summatives_taken):\n",
    "  \n",
    "  list_summative_grades = []\n",
    "  \n",
    "  summative_grades = 0\n",
    "  for i in range(summatives_taken):\n",
    "      summative_grades = int(input(\"Enter summative grades: \"))\n",
    "      if summative_grades < 0 or summative_grades > 100:\n",
    "          print(\"Sorry, I can only accept values under 100 or above 0.\")\n",
    "      while summative_grades < 0 or summative_grades > 100:\n",
    "          summative_grades = int(input(\"Enter summative grades: \"))\n",
    "      list_summative_grades.append(summative_grades)\n",
    "  list_summative_grades.sort()\n",
    "  \n",
    "  print(\"Lowest Grade: \" + str(list_summative_grades[0]))\n",
    "  print(\"Highest Grade: \" + str(list_summative_grades[-1]))\n",
    "  summative_total = 0\n",
    "  for i in range(summatives_taken):\n",
    "      summative_total += int(list_summative_grades[i])\n",
    "      i += 1\n",
    "  summative_average = summative_total/summatives_taken\n",
    "  print(\"Your summative average is around: \" + str(summative_average))\n",
    "  sumtimesweight = summative_average * (percentsummative/100)  \n",
    "  return sumtimesweight\n",
    "\n",
    "def formative_calculations(percentformative, formatives_taken):\n",
    "  #This list can be used to store the values the user will enter.\n",
    "  list_formative_grades = []\n",
    "  formative_grades = 0\n",
    "  for i in range(formatives_taken):\n",
    "      formative_grades = int(input(\"Enter formative grades: \"))\n",
    "      if formative_grades < 0 or formative_grades > 100:\n",
    "          print(\"Sorry, I can only accept values under 100 or above 0.\")\n",
    "      while formative_grades < 0 or formative_grades > 100:\n",
    "          formative_grades = int(input(\"Enter formative grades: \"))\n",
    "      list_formative_grades.append(formative_grades)\n",
    "      list_formative_grades.sort()\n",
    "  print(\"Lowest Grade: \" + str(list_formative_grades[0]))\n",
    "  print(\"Highest Grade: \" + str(list_formative_grades[-1]))\n",
    "  formative_total = 0\n",
    "  for i in range(formatives_taken):\n",
    "    formative_total += int(list_formative_grades[i])\n",
    "\n",
    "  formative_average = formative_total/formatives_taken\n",
    "  print(\"Your formative average is around: \" + str(formative_average))\n",
    "  formtimesweight = formative_average  * (percentformative/100)\n",
    "  return formtimesweight\n",
    "\n",
    "\n",
    "def final_summative(summative_final_calc, formative_final_calc):\n",
    "  print(\"Your Summative average X Summative Weight = \" + str(summative_final_calc))\n",
    "  print(\"Your Formative average X Summative Weight = \" + str(formative_final_calc))\n",
    "  final_grade = summative_final_calc + formative_final_calc\n",
    "  return final_grade\n",
    "    \n",
    "def letter_graded(final_grade):\n",
    "  while True:\n",
    "    if final_grade >= 89.5:\n",
    "      print(\"Your final letter grade is an A\")\n",
    "      return False\n",
    "    elif final_grade >= 79.5:\n",
    "      print(\"Your final letter grade is a B\")\n",
    "      return False\n",
    "    elif final_grade >= 69.5:\n",
    "      print(\"Your final letter grade is a C\")\n",
    "      return False\n",
    "    else:\n",
    "      print(\"Your final letter grade is a F.\")\n",
    "      return False\n",
    "\n",
    "classname, percentsummative, percentformative = percent_input()\n",
    "summatives_taken = summative_input()\n",
    "\n",
    "\n",
    "summative_final_calc = summative_calculations(percentsummative, summatives_taken)\n",
    "\n",
    "\n",
    "formatives_taken = formative_input()\n",
    "formative_final_calc = formative_calculations(percentformative, formatives_taken)\n",
    "final_grade = final_summative(summative_final_calc, formative_final_calc)\n",
    "  \n",
    "print(\"Your final grade calculation for \" + classname + \" is: \" + str(final_grade))\n",
    "\n",
    "letter_graded(final_grade)\n",
    "\n",
    "\n",
    "#Outputs will be displayed by text onto a console when put into a coding platform. The code will ask for user input which can be answered through entering the data by text on the console. After all the inputs and calculations have been ran through, the code will display the final grade of the class and the letter grade.\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
